# Generated by Django 5.2.8 on 2025-12-05 02:31

from django.db import migrations, models
import django.utils.timezone


def migrate_notes_forward(apps, schema_editor):
    """Migrate old name+body to new content field"""
    ProjectNote = apps.get_model('project', 'ProjectNote')
    
    for note in ProjectNote.objects.all():
        # Combine name and body into content
        content_parts = []
        
        # Get old field values if they exist
        if hasattr(note, 'name') and note.name:
            content_parts.append(note.name)
        if hasattr(note, 'body') and note.body:
            content_parts.append(note.body)
        
        # Set content field
        if content_parts:
            note.content = '\n\n'.join(content_parts)
        else:
            note.content = 'Migrated note'  # Fallback if both are empty
        
        # Set timestamps if not already set
        if not note.created_at:
            note.created_at = django.utils.timezone.now()
        
        note.save()


def migrate_notes_backward(apps, schema_editor):
    """Reverse migration - split content back to name+body"""
    ProjectNote = apps.get_model('project', 'ProjectNote')
    
    for note in ProjectNote.objects.all():
        if hasattr(note, 'content') and note.content:
            # Split content: first line = name, rest = body
            parts = note.content.split('\n\n', 1)
            note.name = parts[0][:255] if parts else 'Note'
            note.body = parts[1] if len(parts) > 1 else ''
            note.save()


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_projectfile_projectnote'),
    ]

    operations = [
        # Step 1: Add new fields (nullable first)
        migrations.AddField(
            model_name='projectnote',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectnote',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='projectnote',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, blank=True),
        ),
        
        # Step 2: Migrate data from old fields to new fields
        migrations.RunPython(migrate_notes_forward, migrate_notes_backward),
        
        # Step 3: Remove old fields
        migrations.RemoveField(
            model_name='projectnote',
            name='name',
        ),
        migrations.RemoveField(
            model_name='projectnote',
            name='body',
        ),
        
    ]
