# Generated by Django 5.2.8 on 2025-12-05 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_comment_reminder_sharelink_alter_project_options_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='projectnote',
            index=models.Index(fields=['project', '-created_at'], name='project_pro_project_346e0a_idx'),
        ),
    ]
